version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: db_develop
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_develop:/data/db/develop
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root4321

volumes:
  mongodb_data_develop:
