version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: db_test
    ports:
      - "27017:37017"
    volumes:
      - mongodb_data_test:/data/db/test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root4321

volumes:
  mongodb_data_test:
