version: "3.9"
services:
  db:
    image: mysql
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Passw#01
      MYSQL_DATABASE: db_ventas
    volumes:
      - mysql_db:/var/lib/mysql

volumes:
  mysql_db: